[package]
name = "fitsio"
version = "0.3.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "Rust implmentation of astronomy fits file handling"
homepage = "https://github.com/mindriot101/rust-fitsio"
repository = "https://github.com/mindriot101/rust-fitsio"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/crate/fitsio"

[dependencies]
libc = "0.2.11"
fitsio-sys = { version = "0.2.1", path = "../fitsio-sys" }

[dev-dependencies]
tempdir = "0.3.4"
