[package]
name = "fitsio"
version = "0.8.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "Rust implmentation of astronomy fits file handling"
homepage = "https://github.com/mindriot101/rust-fitsio"
repository = "https://github.com/mindriot101/rust-fitsio"
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/fitsio"
categories = ["external-ffi-bindings", "science"]

[dependencies]
libc = "0.2.11"
fitsio-sys = { version = "0.3.0", path = "../fitsio-sys" }
clippy = { version = "0.0.108", optional = true }

[dev-dependencies]
tempdir = "0.3.4"

[features]
default = []
