# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/mindriot101/rust-fitsio"

[version]
current = "0.18.0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "Cargo.toml"

[[file]]
src = "src/lib.rs"

[[file]]
src = "../README.md"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
cmd = "grep -q {new_version} ../CHANGELOG.md"
name = "check changelog"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
[[after_push]]
cmd = "cargo publish"
name = "publish"
