language: rust
script: bash ./bin/test
sudo: false

rust:
  - stable
  - beta
  - nightly

cache:
  directories:
    - $HOME/.cargo

addons:
  apt:
    packages:
      - llvm-3.9-dev
      - libcfitsio3-dev
      - pkg-config

# XXX this does not work at the moment
# after_success: |
#   sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libbfd-dev &&
#   wget https://github.com/SimonKagstrom/kcov/archive/v31.zip &&
#   unzip v31.zip && mkdir kcov-31/build && cd kcov-31/build && cmake .. && make &&
#   sudo make install && cd ../.. &&
#   kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --verify target/kcov target/debug/fitsio-*

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af85dff20a27bf480a91
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# vim: sw=2:ts=2
