language: rust
sudo: false
install: rustup component add clippy
script: bash ./bin/test

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: test
      install: rustup component add clippy
      before_script: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
          cargo install cargo-tarpaulin
        fi
      script: bash ./bin/test
      after_success: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
          cd fitsio
          cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
        fi

    - stage: sanitize
      script: bash ./bin/run_sanitizers.sh
      rust: nightly

stages:
  - test
  - sanitize

rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - llvm-3.9-dev
      - libcfitsio3-dev
      - pkg-config
        # Install this for tarpaulin
      - libssl-dev

# XXX this does not work at the moment
# after_success: |
#   sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libbfd-dev &&
#   wget https://github.com/SimonKagstrom/kcov/archive/v31.zip &&
#   unzip v31.zip && mkdir kcov-31/build && cd kcov-31/build && cmake .. && make &&
#   sudo make install && cd ../.. &&
#   kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --verify target/kcov target/debug/fitsio-*

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af85dff20a27bf480a91
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always

# vim: sw=2:ts=2
