language: rust
script: bash ./test_all.sh

rust:
  - stable
  - beta
  - nightly

sudo: required

before_install:
  - bash ./travis/install_cfitsio.sh

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libbfd-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/v31.zip &&
  unzip v31.zip && mkdir kcov-31/build && cd kcov-31/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --verify target/kcov target/debug/fitsio-*
