[package]
name = "fitsioexample"
edition = "2018"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
fitsio = { path = "../../fitsio", features = ["array"] }
ndarray = ">=0.8"
