[package]
name = "fitsioexample"
edition = "2018"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
fitsio = { version = "0.19.0", path = "../../fitsio", features = ["array"] }
ndarray = "0.15.0"
