---
- name: Install required packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ required_packages }}"
  become: yes

- name: Install rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain {{ rust_toolchain }} -y
  args:
    creates: /home/vagrant/.cargo/bin/cargo

