[package]
name = "fitsio-sys"
version = "0.5.0"
edition = "2018"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "FFI wrapper around cfitsio"
homepage = "https://github.com/simonrw/rust-fitsio"
repository = "https://github.com/simonrw/rust-fitsio"
readme = "README.md"
license = "MIT/Apache-2.0"
build = "build.rs"
documentation = "https://docs.rs/fitsio-sys"
categories = ["external-ffi-bindings", "science"]
links = "cfitsio"

[features]
fitsio-src = []

[build-dependencies]
pkg-config = "0.3.16"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
