[package]
name = "fitsio-sys"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "FFI wrapper around cfitsio"
homepage = "https://github.com/mindriot101/rust-cfitsio"
repository = "https://github.com/mindriot101/rust-cfitsio"
license = "MIT/Apache-2.0"

[dependencies]
libc = "0.2.11"

[dev-dependencies]
tempdir = "0.3.4"
