[package]
name = "fitsio-sys"
version = "0.2.2"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
description = "FFI wrapper around cfitsio"
homepage = "https://github.com/mindriot101/rust-fitsio"
repository = "https://github.com/mindriot101/rust-fitsio"
license = "MIT/Apache-2.0"
build = "build.rs"
documentation = "https://docs.rs/fitsio-sys"

[dependencies]
libc = "0.2.11"

[dev-dependencies]
tempdir = "0.3.4"

[build-dependencies]
pkg-config = "0.3"
