name: Test the package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
          - rust: beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
            llvm-dev \
            libcfitsio-dev \
            pkg-config \
            libssl-dev \
            python3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: python3 ./bin/test --rust-version ${{matrix.rust}} --test all

  macos-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
          - rust: beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          brew install cfitsio python3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: python3 ./bin/test --rust-version ${{matrix.rust}} --test all

  linux-armv7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: armv7-unknown-linux-gnueabihf

      - name: Test the code
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target armv7-unknown-linux-gnueabihf --manifest-path fitsio/Cargo.toml
