name: Test the package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { test: workspace, rust: stable, allow_failures: false }
          - { test: full-example, rust: stable, allow_failures: false }
          - { test: array, rust: stable, allow_failures: false }
          - { test: fitsio-src, rust: stable, allow_failures: false }
          - { test: book-examples, rust: stable, allow_failures: false }
          - { test: clippy, rust: stable, allow_failures: false }
          - { test: bindgen, rust: stable, allow_failures: false }
          - { test: workspace, rust: beta, allow_failures: false }
          - { test: full-example, rust: beta, allow_failures: false }
          - { test: array, rust: beta, allow_failures: false }
          - { test: fitsio-src, rust: beta, allow_failures: false }
          - { test: book-examples, rust: beta, allow_failures: false }
          - { test: clippy, rust: beta, allow_failures: false }
          - { test: bindgen, rust: beta, allow_failures: false }
          - { test: workspace, rust: nightly, allow_failures: true }
          - { test: full-example, rust: nightly, allow_failures: true }
          - { test: array, rust: nightly, allow_failures: true }
          - { test: fitsio-src, rust: nightly, allow_failures: true }
          - { test: book-examples, rust: nightly, allow_failures: true }
          - { test: clippy, rust: nightly, allow_failures: true }
          - { test: bindgen, rust: nightly, allow_failures: true }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
            llvm-dev \
            libcfitsio-dev \
            pkg-config \
            libssl-dev \
            python3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: python3 ./bin/test --rust-version ${{matrix.rust}} --test ${{matrix.test}}
        continue-on-error: ${{matrix.allow_failures}}

  macos-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { test: workspace, rust: stable, allow_failures: false }
          - { test: full-example, rust: stable, allow_failures: false }
          - { test: array, rust: stable, allow_failures: false }
          - { test: fitsio-src, rust: stable, allow_failures: false }
          - { test: book-examples, rust: stable, allow_failures: false }
          - { test: clippy, rust: stable, allow_failures: false }
          - { test: bindgen, rust: stable, allow_failures: false }
          - { test: workspace, rust: beta, allow_failures: false }
          - { test: full-example, rust: beta, allow_failures: false }
          - { test: array, rust: beta, allow_failures: false }
          - { test: fitsio-src, rust: beta, allow_failures: false }
          - { test: book-examples, rust: beta, allow_failures: false }
          - { test: clippy, rust: beta, allow_failures: false }
          - { test: bindgen, rust: beta, allow_failures: false }
          - { test: workspace, rust: nightly, allow_failures: true }
          - { test: full-example, rust: nightly, allow_failures: true }
          - { test: array, rust: nightly, allow_failures: true }
          - { test: fitsio-src, rust: nightly, allow_failures: true }
          - { test: book-examples, rust: nightly, allow_failures: true }
          - { test: clippy, rust: nightly, allow_failures: true }
          - { test: bindgen, rust: nightly, allow_failures: true }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          brew install cfitsio python3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: python3 ./bin/test --rust-version ${{matrix.rust}} --test ${{matrix.test}}
        continue-on-error: ${{matrix.allow_failures}}

  linux-armv7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: armv7-unknown-linux-gnueabihf

      - name: Test the code
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target armv7-unknown-linux-gnueabihf --manifest-path fitsio/Cargo.toml
