name: Test the package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { test: basic, rust: stable }
          - { test: bindgen, rust: stable }
          - { test: full_example, rust: stable }
          - { test: feature_array, rust: stable }
          - { test: feature_fitsio_src, rust: stable }
          - { test: book_examples, rust: stable }
          - { test: basic, rust: nightly }
          - { test: bindgen, rust: nightly }
          - { test: full_example, rust: nightly }
          - { test: feature_array, rust: nightly }
          - { test: feature_fitsio_src, rust: nightly }
          - { test: book_examples, rust: nightly }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
            llvm-dev \
            libcfitsio-dev \
            pkg-config \
            libssl-dev

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: bash ./bin/test
        env:
          RUST_VERSION: ${{matrix.rust}}
          TEST_TO_RUN: ${{matrix.test}}

  macos-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { test: basic, rust: stable }
          - { test: bindgen, rust: stable }
          - { test: full_example, rust: stable }
          - { test: feature_array, rust: stable }
          - { test: feature_fitsio_src, rust: stable }
          - { test: book_examples, rust: stable }
          - { test: basic, rust: nightly }
          - { test: bindgen, rust: nightly }
          - { test: full_example, rust: nightly }
          - { test: feature_array, rust: nightly }
          - { test: feature_fitsio_src, rust: nightly }
          - { test: book_examples, rust: nightly }
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          brew install cfitsio

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: Test the code
        run: bash ./bin/test
        env:
          RUST_VERSION: ${{matrix.rust}}
          TEST_TO_RUN: ${{matrix.test}}
